name: tweet-first-merge
description: >
  GitHub Action to tweet in celebration of contributor's first merged PR
author: Nick Taylor, Matthew Foley
branding:
  icon: git-pull-request
  color: blue
inputs:
  template:
    description: Template Message To Tweet
    required: true
    # %USER% will be replaced with `twitter_username` from GitHub
    default: >
      Congrats on the first merge, @%handle%!

      %pr_url%

      %user_url%
runs:
  using: composite
  # In this step we want to do the following:
  # 1) Gather GitHub Handle
  # 2) Gather twitter handle from GitHub profile
  # 3) Check whether this is the first PR for this user on this org
  #   github.com/search?q=repo:$REPO author:$LOGIN is:pull-request
  # 4) If all is good, pass non-blank string to output.
  steps:
    - id: validate
      if: ${{ github.event.pull_request.merged }}
      shell: bash
      env:
        TEMPLATE: ${{ inputs.template }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        LOGIN=${{ github.event.pull_request.user.login }}
        USER_URL=${{ github.event.pull_request.user.html_url }}
        PR_URL=${{ github.event.pull_request.html_url}}
        HANDLE="$(curl -s H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$LOGIN | jq .twitter_username | tr -d \")"
        REPO=${{ github.event.repository.full_name }}
        COUNT="$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/search/issues?q=repo%3A$REPO+author%3A$LOGIN+is%3Apull-request+is%3Amerged)"
        FIRST="$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/search/issues?q=repo%3A$REPO+author%3A$LOGIN+is%3Apull-request+is%3Amerged | jq '.total_count <= 1')"
        TWEET=""

        echo "HANDLE $HANDLE"
        echo "COUNT $COUNT"
        echo "FIRST $FIRST"

        if [ "$HANDLE" != "null" ] && [ "$FIRST" = "true" ]; then
          # need to use different delimiter in sed since URL will have /
          TWEET="${TEMPLATE/\%handle%/$HANDLE}"
          TWEET="${TWEET/\%pr_url%/$PR_URL}"
          TWEET="${TWEET/\%user_url%/$USER_URL}"
        fi
        echo "::set-output name=tweet::$TWEET"
        echo $TWEET
    - id: tweet
      if: ${{ steps.validate.outputs.tweet != ''}}
      shell: bash
      env:
        TWEET: ${{ steps.validate.outputs.tweet }}
      run: |
        echo "Found Tweet: $TWEET"
#      uses: snow-actions/tweet@v1.1.1
#      env:
#        CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#        CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
#        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#        ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
#      with:
#          status: ${{ steps.validate.outputs.tweet }}
