name: tweet-first-merge
description: >
  GitHub Action to tweet in celebration of contributor's first merged PR
author: Nick Taylor, Matthew Foley
branding:
  icon: git-pull-request
  color: blue
inputs:
  template-message:
    description: Template Message To Tweet
    required: true
    # %USER% will be replaced with `twitter_username` from GitHub
    default: >
      Congrats on the first merge, @%USER%!
