name: tweet-first-merge
description: >
  GitHub Action to tweet in celebration of contributor's first merged PR
author: Nick Taylor, Matthew Foley
branding:
  icon: git-pull-request
  color: blue
inputs:
  template:
    description: Template Message To Tweet
    required: true
    # %USER% will be replaced with `twitter_username` from GitHub
    default: >
      Congrats on the first merge, @%handle%!

      %url%
runs:
  using: composite
  # In this step we want to do the following:
  # 1) Gather GitHub Handle
  # 2) Gather twitter handle from GitHub profile
  # 3) Check whether this is the first PR for this user on this org
  #   github.com/search?q=repo:$REPO author:$LOGIN is:pull-request
  # 4) If all is good, pass non-blank string to output.
  steps:
    - id: validate
      shell: bash
      env:
        TEMPLATE: ${{ inputs.template }}
      run: |
        LOGIN=${{ github.event.pull_request.user.login }}
        URL=${{ github.event.pull_request.user.html_url }}
        HANDLE="$(curl -s H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$LOGIN | jq .twitter_username | tr -d \")"
        REPO=${{ github.event.repository.full_name }}
        FIRST="$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/search/issues?q=repo%3A$REPO+author%3A$LOGIN+is%3Apull-request+is%3Amerged | jq '.total_count <= 1')"
        TWEET=""
        if [ "$HANDLE" != "null" ] && [ "$FIRST" = "true" ]; then
          # need to use different delimiter in sed since URL will have /
          TWEET="${TEMPLATE/\%handle%/$HANDLE}"
          TWEET="${TWEET/\%url%/$URL}"
        fi
        echo "::set-output name=tweet::$TWEET"
        echo $TWEET
