name: tweet-first-merge
description: >
  GitHub Action to tweet in celebration of contributor's first merged PR
author: Nick Taylor, Matthew Foley
branding:
  icon: git-pull-request
  color: blue
inputs:
  template-message:
    description: Template Message To Tweet
    required: true
    # %USER% will be replaced with `twitter_username` from GitHub
    default: >
      Congrats on the first merge, @%USER%!
runs:
  using: composite
  steps:
    - id: validate
      shell: bash
      run: |
        LOGIN=${{ github.event.pull_request.user.login }}
        HANDLE="$(curl -s H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$LOGIN | jq .twitter_username | tr -d \")"
        echo $HANDLE